---

version: '2.2'

services:
  geth:
    build:
      context: ./les-client-rpc
    networks:
      eth:
        ipv4_address: 10.99.172.2
    restart: always
    stop_grace_period: 3m
    stop_signal: SIGINT
    container_name: "geth-light"
    expose:
      - "30303"
      - "8545"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"

  proxy:
    build:
      context: ./proxy
    ports:
      - "8545:8545"
    networks:
      eth:
        ipv4_address: 10.99.172.3
    restart: always
    container_name: "openresty"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"

networks:
  eth:
    ipam:
      driver: default
      config:
        - subnet: 10.99.172.0/24